import type { CollectionConfig } from 'payload'

export const Media: CollectionConfig = {
  slug: 'media',
  access: {
    read: () => true,
  },
  admin: {
    description: 'All images used across the site. Alt text is required for accessibility and SEO.',
  },
  upload: {
    // When S3/R2 is configured, the storage plugin serves these; otherwise local disk.
    staticDir: 'media',
    mimeTypes: ['image/*'],
    // Responsive sizes generated by sharp. next/image requests the best fit.
    imageSizes: [
      { name: 'thumbnail', width: 400 },
      { name: 'card', width: 768 },
      { name: 'feature', width: 1280 },
      { name: 'hero', width: 1920 },
    ],
    focalPoint: true,
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
      required: true,
      admin: {
        description: 'Describe the image for screen readers and search engines.',
      },
    },
    {
      name: 'caption',
      type: 'text',
      admin: {
        description: 'Optional caption shown in galleries and lightboxes.',
      },
    },
    {
      name: 'credit',
      type: 'text',
      admin: {
        description: 'Optional photographer / source credit.',
      },
    },
  ],
}
